before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
 - sudo apt-get update
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
# - sudo apt-get install -y libappindicator1 fonts-liberation libfontconfig1 libstdc++6 lsb-base
# - sudo apt-get upgrade -y -f fonts-liberation libfontconfig1 libstdc++6 lsb-base
# - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# - sudo dpkg -i -f -y google-chrome*.deb
language: node_js
node_js:
  - "6"